name: Update Streak Stats Image

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  update-streak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create assets directory if not exists
        run: mkdir -p assets

      - name: Download streak stats image
        run: |
          curl -o assets/streak-stats.svg "https://github-readme-streak-stats.herokuapp.com?user=nakulmitra&theme=vue"

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/streak-stats.svg
          git commit -m "Update streak stats [auto]"
          git push
