name: Update Tutorial Repo Stats
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: nakulmitra/github-readme-youtube-cards@main
        with:
          channel_id: UCrGahz8XoaUdvH5x9QkWdEg
          lang: en
          comment_tag_name: YOUTUBE-CARDS
          max_videos: 6
          card_width: 250
          border_radius: 5
          background_color: "#0dffffff1117"
          title_color: "#24292f"
          stats_color: "#57606a"
          theme_context_light: '{ "background_color": "#ffffff", "title_color": "#24292f", "stats_color": "#57606a" }'
          theme_context_dark: '{ "background_color": "#0d1117", "title_color": "#ffffff", "stats_color": "#dedede" }'
          max_title_lines: 2
          commit_message: "docs(readme): Update YouTube cards"
          readme_path: README.md
          output_only: false
          output_type: markdown